### ISSUE TITLE
The problem when I try to run GraphletsConstraints.py 

### ISSUE THREAD

**Issue by XX-Official** [Yanivmd/TRACY#1]
When I try to run GraphletsConstraints.py, a problem happened.

Traceback (most recent call last):
  File "/home/xx/SourceCode/Modify/TRACY/GraphletsConstraints.py", line 323, in <module>
    selfTest()
  File "/home/xx/SourceCode/Modify/TRACY/GraphletsConstraints.py", line 227, in selfTest
    gc.printSol(gc.getSolution())
  File "/home/xx/SourceCode/Modify/TRACY/GraphletsConstraints.py", line 151, in getSolution
    self.callSol()
  File "/home/xx/SourceCode/Modify/TRACY/GraphletsConstraints.py", line 121, in callSol
    self.problem.addVariables([tarName], domain)
  File "/home/xx/.conda/envs/python27/lib/python2.7/site-packages/constraint/__init__.py", line 201, in addVariables
    self.addVariable(variable, domain)
  File "/home/xx/.conda/envs/python27/lib/python2.7/site-packages/constraint/__init__.py", line 167, in addVariable
    raise ValueError(msg)
ValueError: Tried to insert duplicated variable 'm2-1_TAR'

**Comment by Yanivmd** [comment]
This is a problem, but it should not affect your ability to run TRACY.
Why are you running GraphletsConstraints.py directly? GraphletsConstraintsNG should be the only file used by the project.
(findClonesCONS-NDP.py is also deprecated).
